
(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const articles=$$('.chapter'), ids=new Set(articles.map(a=>a.id)), KEY='system-design-handbook-progress-v1';
let state={version:1,lastChapter:'start',chapters:{}},storageOK=true,toastTimer;
function say(t){$('#toast').textContent=t;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',4500)}
function clean(data){if(!data||data.version!==1||!data.chapters||typeof data.chapters!=='object'||Array.isArray(data.chapters))throw Error('Invalid progress file');const out={version:1,lastChapter:ids.has(data.lastChapter)?data.lastChapter:'start',chapters:{}};for(const id of ids){const v=data.chapters[id];if(!v)continue;if(!['new','reading','read','explain'].includes(v.status)||typeof v.notes!=='string'||v.notes.length>200000)throw Error('Invalid chapter data');out.chapters[id]={status:v.status,notes:v.notes}}return out}
try{const saved=localStorage.getItem(KEY);if(saved)state=clean(JSON.parse(saved))}catch(e){storageOK=false}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){if(storageOK)say('Browser saving unavailable. Export progress to keep your notes.');storageOK=false}}
function refresh(){let count=0;for(const a of articles){const v=state.chapters[a.id]||{status:'new',notes:''};a.querySelector('.status').value=v.status;a.querySelector('.notes').value=v.notes;const done=['read','explain'].includes(v.status);if(done)count++;const n=$('.chapter-link[data-chapter="'+a.id+'"] .nav-state');n.textContent=done?'✓':v.status==='reading'?'◐':'○'}$('#progress').value=count;$('#progress-label').textContent=count+' of '+articles.length+' chapters read'}
function closeMenu(){$('#sidebar').classList.remove('open');$('#shade').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}
function route(){let hash;try{hash=decodeURIComponent(location.hash.slice(1))}catch(e){hash='start'}const target=document.getElementById(hash),a=target?.closest('article')||document.getElementById(state.lastChapter)||articles[0];for(const x of articles)x.hidden=x!==a;$$('.chapter-link').forEach(n=>{const active=n.dataset.chapter===a.id;n.classList.toggle('active',active);if(active)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current')});$('#results').hidden=true;$('#search').value='';state.lastChapter=a.id;save();closeMenu();document.title=a.querySelector('h1').textContent+' · System Design';if(target&&target!==a)requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));else window.scrollTo(0,0)}
window.addEventListener('hashchange',route);
$$('.status,.notes').forEach(el=>el.addEventListener(el.classList.contains('notes')?'input':'change',()=>{const id=el.dataset.id,a=document.getElementById(id);state.chapters[id]={status:a.querySelector('.status').value,notes:a.querySelector('.notes').value};save();if(el.classList.contains('status'))refresh()}));
$('#menu').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#shade').classList.toggle('open',open);$('#menu').setAttribute('aria-expanded',String(open))};$('#shade').onclick=closeMenu;
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
$$('.chapter-link').forEach(a=>a.addEventListener('click',()=>{if(location.hash===a.getAttribute('href'))route()}));
const index=$$('.concept').map(s=>({id:s.id,title:s.querySelector('h2').textContent,chapter:s.closest('article').querySelector('h1').textContent,text:[...s.children].filter(x=>!x.classList.contains('concept-heading')).map(x=>x.textContent).join(' ')}));
let searchTimer;$('#search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,120)});
function search(){const q=$('#search').value.trim().toLowerCase();if(!q){route();return}const terms=q.split(/\s+/);let found=index.filter(s=>terms.every(t=>(s.title+' '+s.chapter+' '+s.text).toLowerCase().includes(t)));found.sort((a,b)=>Number(b.title.toLowerCase().includes(q))-Number(a.title.toLowerCase().includes(q)));const box=$('#results');box.replaceChildren();box.hidden=false;articles.forEach(a=>a.hidden=true);const h=document.createElement('h2');h.textContent=found.length+' matching sections';box.append(h);const back=document.createElement('button');back.className='search-dismiss';back.textContent='← Return to reading';back.onclick=route;box.append(back);if(!found.length){const p=document.createElement('p');p.className='empty';p.textContent='No match. Try a shorter phrase such as “retry”, “index”, or “fan-out”.';box.append(p)}for(const s of found.slice(0,80)){const a=document.createElement('a');a.href='#'+s.id;a.className='result';const t=document.createElement('strong');t.textContent=s.title;const c=document.createElement('small');c.textContent=s.chapter;const p=document.createElement('p');const pos=s.text.toLowerCase().indexOf(terms[0]);const from=Math.max(0,pos-65);p.textContent=(from?'…':'')+s.text.slice(from,from+240)+'…';a.append(t,c,p);a.onclick=()=>{if(location.hash==='#'+s.id)route()};box.append(a)}window.scrollTo(0,0)}
function dialog(text,title='Take this to your tutor'){$('#dialog-title').textContent=title;$('#copy-text').value=text;$('#copy-dialog').showModal();$('#copy-text').focus();$('#copy-text').select()}
const tutor='Act as my patient system design tutor. My experience is very basic. My primary goal is interviews; my secondary goal is designing better systems at work. I am reading a detailed handbook and asking for help on this passage. Explain ONE small idea at a time, using a concrete example, then pause for my questions. Explain before quizzing. Stay with my confusion until I am satisfied. Give hints before solutions during exercises. Correct inaccuracies in the passage if you find them, and distinguish assumptions from guarantees. Do not treat exposure as mastery.';
let selection='';document.addEventListener('selectionchange',()=>{const sel=window.getSelection();if(sel&&sel.toString().trim()&&sel.anchorNode&&$('#main').contains(sel.anchorNode))selection=sel.toString().trim();else if(!$('#copy-dialog').open)selection=''});
$$('.ask').forEach(b=>{b.addEventListener('pointerdown',()=>{const s=window.getSelection()?.toString().trim();if(s)selection=s});b.onclick=()=>{const sec=b.closest('section'),a=b.closest('article');const passage=selection||[...sec.children].filter(x=>!x.classList.contains('concept-heading')).map(x=>x.innerText).join('\n\n');dialog(tutor+'\n\nHANDBOOK: Edition 1 · September 2026\nCHAPTER: '+a.querySelector('h1').textContent+'\nSECTION: '+sec.querySelector('h2').textContent+'\nREFERENCE: #'+sec.id+'\n\nPASSAGE:\n'+passage+'\n\nMY QUESTION: [Write what is confusing, or ask for a simpler explanation.]');selection=''}});
$$('.checkpoint').forEach(b=>b.onclick=()=>{const a=document.getElementById(b.dataset.id),v=state.chapters[a.id]||{status:'new',notes:''};dialog('SYSTEM DESIGN LEARNING CHECKPOINT\nApproach: detailed notes first; interactive AI help on confusing concepts; interview practice afterward.\nLevel: very basic. Goal: system design interviews, then better design at work.\nHandbook: Edition 1 · September 2026\nChapter: '+a.querySelector('h1').textContent+'\nSelf-reported status: '+v.status+'\nQuestions / evidence:\n'+(v.notes||'No notes recorded.')+'\n\n'+tutor+'\n\nPlease ask which recorded question I want to discuss, or continue from the question I provide.','Chapter checkpoint')});
$('#copy-close').onclick=()=>$('#copy-dialog').close();$('#copy-confirm').onclick=async()=>{const text=$('#copy-text').value;try{await navigator.clipboard.writeText(text);say('Copied. Paste into any LLM.')}catch(e){$('#copy-text').focus();$('#copy-text').select();if(document.execCommand('copy'))say('Copied. Paste into any LLM.');else say('Text selected. Use your keyboard copy command.')}};
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#export').onclick=()=>download('system-design-progress.json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));
$('.import').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#import').click()}});
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5000000)throw Error('File too large');const next=clean(JSON.parse(await f.text()));if(!confirm('Replace the reading status and notes in this browser with this progress file? Export first if you want a backup.'))return;state=next;save();refresh();history.replaceState(null,'','#'+state.lastChapter);route();say('Progress imported.')}catch(err){say('Could not import: use a valid handbook progress JSON file.')}finally{e.target.value=''}};
$('#print').onclick=()=>window.print();refresh();route();if(!storageOK)say('Browser saving unavailable. Export progress before leaving.');
})();
